### ISSUE TITLE
Stuck on "foundation new * -libsass"

### ISSUE THREAD

**Issue by jstummbillig** [foundation/foundation-libsass-template#20]
On Windows 8.1 with current git, ruby (x64) and node (x64), I run into the following issue:

$ foundation new projectname --libsass
Creating ./projectname
       exist  projectname
fatal: destination path 'projectname' already exists and is not an empty directory.
Installing dependencies with bower...
bower                            retry Request to https://bower.herokuapp.com/packages/jquery-placeholder failed with ETIMEDOUT, retrying in 1.5s

Now, if i recall correctly, last time (several month ago) this was worked around by downgrading to an older version of node. I guess I'm going to do that again, but I guess we can all agree that really shouldn't be necessary. Any suggestions or fixes would be appreciated.

**Comment by quakenul** [comment]
Just wanna confirm that, again, downgrading to nodejs v0.10.33 solves the issue (but that's not really solving the issue ;))

**Comment by DanielRuf** [comment]
Closing as outdated.
