### ISSUE TITLE
node-sass cannot be downloaded on windows

### ISSUE THREAD

**Issue by vandanagopal** [foundation/foundation-libsass-template#22]
Hi, I need your help, I followed the quick setup instructions mentioned by you on Windows. After git clone, when I do npm install on command line, I get the error - 

> node-sass@2.0.1 install C:\Projects\myfoundation\foundation-libsass-template\n
> ode_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-bina
ries/v2.0.1/win32-x64-node-3.3/binding.node

> node-sass@2.0.1 postinstall C:\Projects\myfoundation\foundation-libsass-templa
> te\node_modules\node-sass
> node scripts/build.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'C:\Projects\myfoundation\foundation-libsass-template\
node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:951:3
Build failed
grunt-sass@0.18.1 node_modules\grunt-sass
├── object-assign@2.1.1
└── each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.1)

grunt@0.4.5 node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── colors@0.6.2

Would very much appreciate your help in fixing this. Thanks.

**Comment by vandanagopal** [comment]
Finally found the error - manually go to packages.json and edit the node-sass line and put this instead
"node-sass": "^3.3.3",
since the 2.1.1 node sass doesnt work with nodejs version >4. 
Refer: https://github.com/sass/node-sass/issues/1166

**Comment by DanielRuf** [comment]
Closing as outdated.
